// Food data per 100 g / 100 ml. Carbs exclude fibre, as on UK labels.
// Row: id, name, group, serving g, kcal, protein, carbs, fat, fibre, vegan, serving label, brand, note
const ROWS = [
// id, name, group, serving g, kcal, P, C, F, Fi, vegan, servingLabel, brand, note   (values per 100 g / 100 ml)
 ["ktc_kala","Kala Chana in Salted Water","Beans & lentils",120,102,6,13,1.6,6,1,"½ tin, drained","KTC"],
 ["ktc_chick","Chick Peas in Salted Water","Beans & lentils",120,116,7.3,15,2.2,3.5,1,"½ tin, drained","KTC","Carbs worked out from the label calories"],
 ["ktc_rajma","Red Kidney Beans (rajma)","Beans & lentils",120,103,8.4,17.4,0.5,6.7,1,"½ tin, drained","KTC"],
 ["ktc_blackeye","Black Eye Beans in Salted Water","Beans & lentils",120,60,4.8,8,0.4,2.4,1,"½ tin, drained","KTC","Carbs worked out from the label calories"],
 ["ktc_butter","Butter Beans","Beans & lentils",120,68,4.3,9.1,0.5,4.8,1,"½ tin, drained","KTC"],
 ["blackbeans","Organic Black Beans","Beans & lentils",120,81,4.1,12.6,0.2,5.6,1,"½ tin, drained","Biona"],
 ["lentils","Ready to Eat Puy Lentils","Beans & lentils",125,148,11,19,1.7,5.2,1,"½ pouch","Merchant Gourmet"],
 ["redlentil","Red Lentils / Masoor Dal (dry)","Beans & lentils",60,342,23.8,56.3,1.3,5,1,"60 g dry","TRS","Calories worked out from the label macros"],
 ["toor","Toor Dal (dry)","Beans & lentils",60,321,21,42,3.5,18,1,"60 g dry","TRS","Label lists carbs including fibre; adjusted to exclude it"],
 ["moong","Mung Dal (dry)","Beans & lentils",60,318,26,35,3.7,20,1,"60 g dry","TRS"],
 ["chanadal","Chana Dal (dry)","Beans & lentils",60,347,22.8,41.7,7.5,10.9,1,"60 g dry","TRS","Listed fat (20.6 g) doesn't match the calories; fat worked out from them"],
 ["urad","Urid Dal (dry)","Beans & lentils",60,298,26,29,1.4,28,1,"60 g dry","TRS","Label lists carbs including fibre; adjusted to exclude it"],
 ["urad_whole","Urid Beans, whole black urad (dry)","Beans & lentils",60,305,24.7,47.8,1.7,18,1,"60 g dry","Natco","Fibre not listed on the label; typical value used"],
 ["rajma_dry","Red kidney beans, dried","Beans & lentils",60,333,23.6,44.8,0.8,15.2,1,"60 g dry","","No brand label found; standard values for dried kidney beans"],
 ["hummus","Houmous Extra","Beans & lentils",30,367,7,9,33,6.2,1,"30 g (2 tbsp)","Sabra"],
 ["arla_lf","Low Fat Natural Cottage Cheese","Cottage & soft cheese",100,71,10,4.2,1.6,0,0,"100 g","Arla"],
 ["arla_nat","Natural Cottage Cheese","Cottage & soft cheese",100,102,10.3,3.1,5.4,0,0,"100 g","Arla"],
 ["daisy","2% Low Fat Cottage Cheese","Cottage & soft cheese",113,80,11.5,4.4,2.2,0,0,"½ cup (113 g)","Daisy","US label, converted to per 100 g"],
 ["phil_pro","Protein Low Fat Soft Cream Cheese","Cottage & soft cheese",30,87,11,4.9,2.5,0.4,0,"30 g (2 tbsp)","Philadelphia"],
 ["eatlean","Protein Cheese, grated","Cottage & soft cheese",30,172,36.3,1.7,3,0,0,"30 g","Eatlean"],
 ["tesco_paneer","Paneer (medium fat)","Cottage & soft cheese",80,247,16.7,5.3,17.5,0,0,"80 g","Tesco"],
 ["paneer","Paneer Block (full fat)","Cottage & soft cheese",80,347,20.9,4.1,27.7,0,0,"80 g","Everest"],
 ["cheddar","Mature Cheddar","Cottage & soft cheese",30,416,25.4,0.1,34.9,0,0,"30 g","Cathedral City"],
 ["milb_straw","High Protein Strawberry Yogurt","Yogurt & milk",200,83,12.4,7.5,0.4,0,0,"200 g pot","Lidl Milbona"],
 ["milb_van","High Protein Vanilla Quark Dessert","Yogurt & milk",200,77,12.5,6.8,0.5,0,0,"200 g pot","Lidl Milbona"],
 ["milb_choc","High Protein Chocolate Pudding","Yogurt & milk",200,76,10,5.2,1.5,0.3,0,"200 g pot","Lidl Milbona"],
 ["milb_drink","High Protein Drink","Yogurt & milk",250,53,8,4.9,0.1,0,0,"250 ml","Lidl Milbona","Check the bottle size on the pack"],
 ["greek","Total 0% Greek Recipe Yoghurt","Yogurt & milk",170,54,10.3,3,0,0,0,"170 g pot","Fage"],
 ["milk","Semi Skimmed Milk","Yogurt & milk",250,49,3.6,4.8,1.7,0,0,"250 ml","Cravendale"],
 ["skim","Skimmed Milk","Yogurt & milk",250,37,3.6,5,0.3,0,0,"250 ml","Cravendale","Carbs worked out from the label calories"],
 ["grahams","The Family Dairy Whole Milk","Yogurt & milk",250,65,3.5,4.7,3.7,0,0,"250 ml","Graham's"],
 ["yeo","Organic Natural Yogurt","Yogurt & milk",150,82,5.1,5.6,4.5,0,0,"150 g","Yeo Valley"],
 ["milb_greek","Creamy Greek Style Natural Yogurt","Yogurt & milk",150,126,4.1,4.6,10,0.5,0,"150 g","Lidl Milbona"],
 ["peaprotein","Pea Protein Powder, unflavoured","Protein powder",30,406,80,0.5,9.1,1.4,1,"30 g scoop","Pulsin"],
 ["cosmix","PB Fudge Fermented Yeast Protein","Protein powder",38,387,63,18,4.4,0,1,"1 scoop (~38 g)","Cosmix","Calories and protein from your recipe (1¼ scoops = 184 kcal, 30 g protein); carbs and fat estimated"],
 ["oats","Rolled Oats","Grains & bread",40,374,11,60,8,9,1,"40 g","Quaker"],
 ["quinoa","Red & White Quinoa (ready to eat)","Grains & bread",125,184,5.8,31,3.2,4,1,"½ pouch","Merchant Gourmet"],
 ["bread","Tasty Wholemeal Medium","Grains & bread",80,221,10,37.8,1.8,6.8,1,"2 slices","Hovis","Carbs worked out from the label calories"],
 ["warb_seed","Seeded Batch","Grains & bread",92,293,10.6,39.7,8.9,6,1,"2 slices","Warburtons"],
 ["hovis_seed","Seed Sensations Seven Seeds","Grains & bread",88,278,10,42,6.6,5.3,1,"2 slices","Hovis"],
 ["wwpasta","Wholewheat Penne (dry)","Grains & bread",75,344,13,64,2,9,1,"75 g dry","Napolina"],
 ["mission_wrap","Wholemeal Tortilla Wrap","Grains & bread",61,304,8.3,47.9,7.2,6.9,1,"1 wrap","Mission"],
 ["laila","Xtra Long Basmati Rice (dry)","Grains & bread",60,375,8.1,84,0.4,0,1,"60 g dry","Laila","Fibre not listed on the label"],
 ["bio_seedy","Super Seedy & Nutty Granola","Grains & bread",50,401,11,48,15,15,1,"50 g","Bio&Me"],
 ["bio_low","Low Sugar Gut Loving Granola","Grains & bread",50,411,12,48,15,18,1,"50 g","Bio&Me"],
 ["cornflakes","Corn Flakes","Grains & bread",30,377,7,84,0.9,3,1,"30 g","Kellogg's","Listing showed calories and protein; carbs, fat and fibre from the standard UK label"],
 ["brownrice","Wholegrain Basmati (microwave)","Grains & bread",125,129,2.8,23.3,2.1,3,1,"½ pouch","Tilda"],
 ["almonds","Whole Almonds","Nuts & seeds",30,580,21.2,5.3,49.9,12.5,1,"30 g handful","Whitworths","Carbs worked out from the label calories"],
 ["cashew","Cashew nuts","Nuts & seeds",30,553,18.2,26.9,43.9,3.3,1,"30 g","","No brand label found; standard values"],
 ["makhana","Makhana (fox nuts / lotus seeds)","Nuts & seeds",15,347,9.7,62.4,0.1,14.5,1,"1.5 cups (15 g)","","No UK brand label found; standard values"],
 ["pb","100% Smooth Peanut Butter","Nuts & seeds",30,580,26,16,43,10,1,"2 tbsp","Whole Earth"],
 ["pumpkin","Pumpkin Seeds","Nuts & seeds",25,544,36.5,1.3,41.7,8.7,1,"25 g","Whitworths"],
 ["hemp","Hemp Seed Hearts","Nuts & seeds",30,569,32.5,9.2,46.3,2.6,1,"3 tbsp","Good Hemp"],
 ["chia","Milled Chia Seeds","Nuts & seeds",20,493,21,11.3,35,22.9,1,"20 g (2 dsp)","Linwoods"],
 ["flax","Organic Milled Flaxseed","Nuts & seeds",20,526,23,6.5,41,20,1,"20 g (2 dsp)","Linwoods"],
 ["peas","Garden Peas (frozen)","Tins & frozen",80,68,4.9,7.5,0.7,6,1,"80 g","Birds Eye"],
 ["ktc_tom","Chopped Tomatoes","Tins & frozen",200,16,1,3,0.2,0.7,1,"½ tin","KTC"],
 ["sweetcorn","Original Sweetcorn (tin, drained)","Tins & frozen",80,77,2.4,12.6,1.2,3,1,"80 g","Green Giant"],
 ["fr_berries","Mixed Berries (frozen)","Tins & frozen",80,47,0.9,7.1,0.2,3,1,"80 g","Lidl Freshona","Fibre not listed; typical berry value used"],
 ["fr_veg","Mixed Vegetables (frozen)","Tins & frozen",80,38,2.3,4.5,0.6,2.5,1,"80 g","Lidl Freshona","Fibre not listed; typical value used"],
 ["oil","100% Italian Extra Virgin Olive Oil","Tins & frozen",10,822,0,0,91.3,0,1,"2 tsp (10 ml)","Filippo Berio"],
 ["ghee","Pure Butter Ghee","Tins & frozen",5,898,0.5,0,100,0,0,"1 tsp (5 g)","KTC"],
 ["schezwan","Schezwan Chutney","Sauces",7,176,2.2,27,6.7,0,1,"1 tsp","Ching's Secret","Carbs worked out from the label calories"],
 ["ketchup","Tomato Ketchup","Sauces",15,104,1.2,23.2,0.1,0,1,"1 tbsp","Heinz"],
 ["chilli_sauce","Tomato Ketchup Sweet Chilli","Sauces",15,126,1.3,29.8,0.2,1,1,"1 tbsp","Heinz"],
 ["honey","Clear Honey","Sauces",7,329,0.4,81.5,0.2,0,0,"1 tsp","Rowse"],
 ["cocoa","Bournville Cocoa Powder","Sauces",4,416,23,16.8,21,34,1,"2 tsp","Cadbury","Carbs worked out from the label calories"],
 ["sf_choc","No Added Sugar Dark Chocolate","Sauces",15,529,8.6,36.8,41.8,9.5,0,"15 g","Sainsbury's","Carbs include 29.7 g polyols (sweeteners)"],
 ["cornflour","Cornflour","Sauces",8,354,0.4,88,0.4,0.4,1,"1 tbsp","Brown & Polson"],
 ["soysauce","Soy Sauce","Hidden",10,90,10.4,6.7,0,0,1,"2 tsp","Kikkoman","Contains soya"],
 ["chilli_oil","Chiu Chow Chilli Oil","Hidden",5,676,3.3,5,70,0,1,"1 tsp","Lee Kum Kee","Made with soybean oil and soy sauce"],
 ["tofu","Organic Tofu Block","Hidden",75,118,13,1,7.1,1.9,1,"75 g","Cauldron","Contains soya"],
 ["broccoli","Broccoli","Fresh fruit & veg",90,34,2.8,4,0.4,2.6,1,"90 g",""],
 ["spinach","Spinach","Fresh fruit & veg",80,23,2.9,1.4,0.4,2.2,1,"80 g",""],
 ["mushroom","Mushrooms","Fresh fruit & veg",80,22,3.1,2.3,0.3,1,1,"80 g",""],
 ["sweetpot","Sweet potato (baked)","Fresh fruit & veg",150,90,2,17.4,0.2,3.3,1,"1 medium",""],
 ["onion","Onion","Fresh fruit & veg",100,40,1.1,7.6,0.1,1.7,1,"1 medium",""],
 ["springonion","Spring onion","Fresh fruit & veg",15,32,1.8,4.7,0.2,2.6,1,"15 g",""],
 ["tomato","Tomatoes, fresh","Fresh fruit & veg",120,18,0.9,2.7,0.2,1.2,1,"1 medium",""],
 ["pepper","Bell pepper","Fresh fruit & veg",80,31,1,3.9,0.3,2.1,1,"½ pepper",""],
 ["potato","Potato (raw weight)","Fresh fruit & veg",175,77,2,15.3,0.1,2.2,1,"1 medium",""],
 ["apple","Apple","Fresh fruit & veg",150,52,0.3,11.4,0.2,2.4,1,"1 medium",""],
 ["banana","Banana","Fresh fruit & veg",120,89,1.1,20.2,0.3,2.6,1,"1 medium",""],
 ["raspberry","Raspberries","Fresh fruit & veg",80,52,1.2,5.4,0.7,6.5,1,"80 g",""],
 ["strawberry","Strawberries","Fresh fruit & veg",100,32,0.7,5.7,0.3,2,1,"100 g (about 7)",""],
 ["avocado","Avocado","Fresh fruit & veg",70,160,2,1.8,14.7,6.7,1,"½ avocado",""],
 ["skyr","Skyr Natural","Yogurt & milk",150,61,10,4,0.2,0,0,"150 g","Arla"],
 ["doublecream","Double cream","Yogurt & milk",30,467,1.7,2.6,50.5,0,0,"2 tbsp (30 ml)","","Standard UK double cream values"],
 ["mozz","Mozzarella","Cottage & soft cheese",30,238,17,2,18,0,0,"30 g","Galbani"],
 ["phil_light","Light Soft Cream Cheese","Cottage & soft cheese",30,147,7.3,5.4,10.7,0,0,"30 g","Philadelphia","Carbs worked out from the label calories"],
 ["besan","Pure Gram Flour (besan)","Beans & lentils",30,334,21.7,50,2.7,11.5,1,"30 g","TRS","Fibre not listed; worked out from the label calories"],
 ["kabuli_dry","Chickpeas / kabuli chana (dry)","Beans & lentils",60,364,19.3,43.3,6,17.4,1,"60 g dry","","No brand label found; standard values for dried chickpeas"],
 ["sourdough","White Ciabattin Sourdough","Grains & bread",50,230,10.1,44.1,0.8,2.9,1,"1 slice (~50 g)","Jason's"],
 ["almondbutter","Smooth Almond Butter","Nuts & seeds",15,650,25,6.5,56,12,1,"1 tbsp","Meridian"],
 ["peanuts","Roasted peanuts","Nuts & seeds",20,587,24.4,13.5,49.7,8,1,"20 g","","No brand label found; standard values"],
 ["sesame","Sesame seeds","Nuts & seeds",10,573,17.7,11.7,49.7,11.8,1,"1 tbsp","","No brand label found; standard values"],
 ["tompaste","Double Concentrate Tomato Purée","Tins & frozen",15,89,4.5,15.6,0.4,2.3,1,"1 tbsp","Napolina"],
 ["sundried","Sun-dried Tomatoes in Oil","Tins & frozen",20,108,1,3.9,9.2,0,1,"20 g","Cooks & Co"],
 ["roastpep","Roasted Red Peppers (jar)","Tins & frozen",75,23,0.8,3.9,0.3,1.5,1,"1 pepper","Cooks & Co","Label shows calories only; other macros are typical values"],
 ["mustardoil","Edible Mustard Oil","Tins & frozen",5,824,0,0,91.6,0,1,"1 tsp","KTC","The online listing's figures don't add up; standard oil values used"],
 ["groundnutoil","Groundnut Oil","Tins & frozen",5,899,0,0,99.9,0,1,"1 tsp","KTC","Standard oil values"],
 ["nutyeast","Engevita B12 Nutritional Yeast","Sauces",5,349,47,19,5,20,1,"1 tbsp","Marigold"],
 ["pesto","Classic Basil Pesto","Sauces",15,462,3.9,9.3,45,1.9,0,"1 tbsp","Sacla'"],
 ["maple","Pure Maple Syrup","Sauces",15,356,0.4,88,0.5,0,1,"1 tbsp","Clarks"],
 ["sugar","Granulated Sugar","Sauces",4,400,0,100,0,0,1,"1 tsp","Tate & Lyle"],
 ["chillipaste","Calabrian chilli paste","Sauces",15,250,2,8,23,5,1,"1 tbsp","","No label found; typical values for chilli paste in oil"],
 ["gochujang","Gochujang Red Pepper Paste","Hidden",15,182,3.5,37,1.7,2.9,1,"1 tbsp","Bibigo","Contains soya"],
 ["soymilk","Soya No Sugar","Hidden",100,33,3.3,0,1.8,0.6,1,"100 ml","Alpro","Soya"],
 ["okra","Okra (bhindi)","Fresh fruit & veg",100,33,1.9,4.3,0.2,3.2,1,"100 g",""],
 ["cucumber","Cucumber","Fresh fruit & veg",100,15,0.7,3.1,0.1,0.5,1,"⅓ cucumber",""],
 ["carrot","Carrot","Fresh fruit & veg",60,41,0.9,6.8,0.2,2.8,1,"1 small",""],
 ["jalapeno","Jalapeño","Fresh fruit & veg",15,29,0.9,3.7,0.4,2.8,1,"1 pepper",""],
 ["ginger","Ginger","Fresh fruit & veg",10,80,1.8,15.8,0.8,2,1,"1 inch",""],
 ["greenchilli","Green chilli","Fresh fruit & veg",5,40,2,7.9,0.2,1.5,1,"1 chilli",""],
 ["coconut","Coconut, fresh grated","Fresh fruit & veg",30,354,3.3,6.2,33.5,9,1,"30 g",""],
 ["butter","Slightly Salted Butter","Yogurt & milk",5,739,0.6,0.7,82,0,0,"1 tsp","Lurpak"],
 ["kala_dry","Kala chana / black chickpeas (dry)","Beans & lentils",60,360,20,45,5,17,1,"60 g dry","","No brand label found; standard values for dried black chickpeas"],
];

export const HIDDEN = new Set(["tofu","soysauce","chilli_oil","gochujang","soymilk"]);

export const FOODS = ROWS.map(a => ({
  id: a[0], name: a[1], group: a[2], serv: a[3],
  n: { k: a[4], p: a[5], c: a[6], f: a[7], fi: a[8] },
  vegan: !!a[9], servLabel: a[10], brand: a[11] || '', note: a[12] || '', builtIn: true,
}));

export const FOOD = Object.fromEntries(FOODS.map(f => [f.id, f]));

export const RECIPES = [
 {id:"makhani",stated:"~230 kcal · ~13 g protein · ~25 g carbs · ~7 g fat",name:"Healthier dal makhani",serves:4,time:"Soak overnight + 45 min",tags:["High protein","High fibre"],
  ing:[["urad_whole",150],["rajma_dry",30],["chanadal",20],["ghee",20],["tomato",180],["tesco_paneer",100]],
  extra:["1 green chilli, 1 bay leaf, ½ tsp turmeric, 1 tsp grated ginger, salt (for pressure cooking)","1 tsp cumin seeds, 1 tsp Kashmiri chilli powder, 1.5 tbsp ginger-garlic paste, 1 tsp garam masala (base)","¾ cup tomato purée = 2 medium tomatoes, puréed","Paneer blended with 3–4 tbsp warm water instead of cream","Tadka: 1 tsp kasuri methi (toasted, powdered), 1.5 tsp Kashmiri chilli powder","Ghee is 2 tsp for the base + 2 tsp for the tadka","About 225 g per serving"],
  steps:["Soak all the dals overnight (or in hot water for 3–4 hours if you forgot). Drain, add fresh water, and pressure cook with the chilli, bay leaf, turmeric, ginger and salt for 6–7 whistles until completely soft. Remove the bay leaf and chilli.","Heat 2 tsp ghee and add the cumin seeds. Add the Kashmiri chilli powder and ginger-garlic paste and cook until fragrant.","Add the tomato purée and cook until the oil separates. Add garam masala, fold in the cooked dals, add hot water, season with salt, cover and simmer 8–10 minutes.","Blend the paneer with the warm water until completely smooth. Pour into the dal and simmer 2–3 minutes.","For the tadka: heat 2 tsp ghee, switch off the flame, add the powdered kasuri methi and Kashmiri chilli powder, and pour straight over the dal."]},
 {id:"rajmawrap",stated:"Not given",name:"Rajma & paneer crispy wrap",serves:1,time:"15 min",tags:["High protein","High fibre"],
  ing:[["ktc_rajma",100],["tesco_paneer",75],["schezwan",7],["mission_wrap",61],["oil",5],["greek",40],["chilli_sauce",15],["tomato",35],["ketchup",8]],
  extra:["Filling: ½ tsp red chilli powder, ¼ tsp black pepper, ½ tsp jeera powder, salt","Yogurt sauce: 2–3 tbsp Greek yogurt + 1 tbsp chilli sauce","Salsa: 2–3 tbsp finely chopped tomato, a handful of fresh coriander, 1 tbsp lemon juice, ½ tbsp ketchup (optional), salt"],
  steps:["Mash the boiled rajma and crumble in the paneer, then mix with the chilli powder, pepper, jeera powder, salt and Schezwan chutney until well combined.","Lightly cook the tortilla on one side. Flip, spread the rajma–paneer mixture evenly over the cooked side, drizzle a little oil, and cook until golden and slightly crispy on both sides.","Mix the Greek yogurt and chilli sauce to make a quick creamy sauce.","In another bowl, mix the tomato, coriander, lemon juice, ketchup and salt to make the salsa.","Layer the sauce and salsa over the tortilla, fold in half, cut, and serve hot."]},
 {id:"cornpot",stated:"315 kcal · 13 g protein · 49 g carbs · 8 g fat",name:"Cheesy corn potatoes",serves:3,time:"25 min + 20 min soak",tags:[],
  ing:[["potato",500],["cornflour",8],["oil",10],["sweetcorn",100],["tesco_paneer",100],["soysauce",10],["honey",14],["onion",60],["springonion",15],["chilli_oil",5]],
  extra:["Salt and pepper to taste","Sauce: 3–4 dried red chillies, soaked (or ¾ tsp chilli powder), 1 garlic clove, 1 zero-salt stock cube or 1 tbsp nutritional yeast (optional), 1 tsp lemon juice, 100 ml warm water","Finish: 2 garlic cloves, minced","Oil is 1 tsp for the potatoes + 1 tsp to finish","Paneer can be swapped for silken tofu","Contains soy sauce and chilli oil (soya). About 250 g per serving."],
  steps:["Soak the potato wedges in water for 20–30 minutes. Drain and pat completely dry.","Toss with the cornflour, salt, pepper and 1 tsp oil.","Air fry at 180°C for 15–16 minutes until golden and crisp, OR bake at 200°C for 30–35 minutes, turning once, OR boil the potatoes whole until fork-tender, slice, toss with the cornflour mix and pan fry lightly until golden at the edges.","Blend the sweetcorn, paneer, chillies, garlic, soy sauce, stock cube, honey, lemon juice, warm water and salt into a smooth, silky purée.","Heat 1 tsp oil and sauté the minced garlic and onion until golden brown.","Add the sauce and cook for 2 minutes on medium heat.","Add the potatoes, toss well, cook for 30 seconds to 1 minute, and switch off the flame.","Finish with spring onion and a drizzle of chilli oil."]},
 {id:"mousse",stated:"225 kcal · 20 g protein · 21 g carbs · 8 g fat",name:"Choco crunch protein mousse",serves:2,time:"10 min + setting",tags:["High protein"],
  ing:[["makhana",15],["cashew",9],["cosmix",47.5],["cocoa",4],["skim",150],["sf_choc",15],["cornflakes",8]],
  extra:["Protein powder: 1¼ scoops of your choice (Cosmix PB Fudge Fermented Yeast Protein used here)","Vanilla essence, a few drops","Monk fruit or sweetener of choice, to taste","About 120 g per serving"],
  steps:["Blend the makhana, cashews, protein powder, cocoa powder, vanilla essence, skimmed milk and sweetener into a thick, mousse-like consistency.","Divide between two mason jars or ramekins. Set in the fridge for a few hours or overnight, or in the freezer for 15–20 minutes.","Meanwhile, melt the sugar-free dark chocolate and stir in the cornflakes.","Spoon the chocolate-cornflake mix over each mousse and put them back in the freezer for 5–10 minutes, until the chocolate sets.","Enjoy!"]},
 {id:"pachadi",name:"Crispy vendakkai pachadi",serves:1,time:"45 min",tags:["High protein","High fibre"],stated:"300 kcal · 25 g protein",
  ing:[["okra",300],["skyr",225],["tomato",240],["oil",5]],
  extra:["½ tsp turmeric, 1 tsp Kashmiri chilli powder, 1 tsp cumin powder, ½ tsp coriander powder, ½ tsp chaat masala","1 tbsp ginger-garlic paste, 1 tsp kasuri methi, salt","Coriander leaves and a squeeze of lemon"],
  steps:["Put the chopped okra in a bowl with the chopped tomatoes, ginger-garlic paste, all the masalas, salt and kasuri methi.","Mix well and tip into the air fryer.","Air fry at 200°C for 40 minutes, taking it out to mix every 10 minutes.","Put the crispy okra in a bowl with the skyr, coriander leaves and lemon juice.","Mix well and enjoy."]},
 {id:"marrytofu",name:"Marry me paneer",serves:3,time:"35 min",tags:["High protein"],stated:"Not given",
  ing:[["tesco_paneer",300],["nutyeast",10],["cornflour",16],["oil",27],["onion",150],["chillipaste",30],["sundried",30],["tompaste",32],["doublecream",60]],
  extra:["Crispy paneer: 2 tsp paprika, 2 tsp Italian seasoning, 2 tsp salt, black pepper","Sauce: 1 tsp red chilli flakes, 2 tbsp minced garlic, 1 tsp paprika, 1 tsp Italian seasoning, ½ cup vegetable broth","Fresh coriander to finish","Serve with steamed rice (not counted)","The original doesn't give servings; set to 3","Olive oil is 1 tbsp for the paneer + 1 tbsp for the sauce. Paneer counted as Tesco medium fat."],
  steps:["Cut the paneer into bite-sized cubes. Add the nutritional yeast, paprika, Italian seasoning, salt, black pepper, cornflour and olive oil, and toss until evenly coated.","Air fry at 200°C (400°F) for 10–12 minutes, shaking halfway, until golden and crisp at the edges (or pan fry in a little oil).","Heat the olive oil in a pan over medium heat. Add the chilli flakes, onion, Calabrian chilli paste, garlic, sun-dried tomatoes, tomato purée, paprika and Italian seasoning. Sauté for about 5 minutes until fragrant.","Pour in the vegetable broth and cream. Stir well and simmer on low for 10 minutes until slightly thickened.","Add the crispy paneer and coriander and toss gently until every piece is coated.","Serve over warm rice."]},
 {id:"chikkar",name:"Chikkar chole",serves:4,time:"Soak overnight + 45 min",tags:["High fibre"],stated:"370 kcal · 14 g protein · 52 g carbs · 13 g fat",
  ing:[["kabuli_dry",250],["potato",150],["yeo",80],["onion",200],["ginger",15],["greenchilli",20],["mustardoil",20],["ghee",14],["sugar",4]],
  extra:["1 bay leaf, a pinch of cooking soda (optional)","½ tsp turmeric, 2 tsp red chilli powder, 2 tsp coriander powder, 1 tbsp chana masala","Tadka: 1 tsp kasuri methi, a pinch of hing, extra ginger juliennes, 2 slit green chillies","Salt to taste, coriander leaves to finish","Curd counted as Yeo Valley natural yogurt. About 280 g per serving."],
  steps:["Soak the chickpeas overnight (8 hours). Drain and rinse well.","Pressure cook the chana with the halved potato, bay leaf, a pinch of cooking soda, salt and enough water to cover: 4–5 whistles on high, then simmer 5 minutes. Let the pressure release naturally.","Blend the potato, 1 tbsp of the cooked chickpeas, the curd and a splash of water to a smooth purée.","Heat the mustard oil until smoking hot. Add the onion, ginger and chopped green chillies and cook until golden.","Add the turmeric, red chilli powder, coriander powder and chana masala. Mix well.","Pour in the curd mix and cook, stirring, until the oil starts to separate.","Add the rest of the chickpeas and their cooking liquid. Season with salt and sugar and simmer a few minutes until thick and mushy.","Finish with a tadka of slit green chillies and ginger juliennes crackled in hot ghee with kasuri methi and a pinch of hing. Pour over, garnish with coriander and serve."]},
 {id:"cinnachia",name:"Cinnamon roll chia pudding",serves:1,time:"10 min + overnight",tags:["High protein","High fibre"],stated:"Not given",
  ing:[["greek",260],["chia",30],["phil_light",20],["almondbutter",20],["maple",30],["milk",10]],
  extra:["Pudding: 200 g Greek yogurt, 1 tsp cinnamon, a splash of vanilla, a pinch of salt, maple syrup to taste","Frosting: 60 g Greek yogurt, 20 g light cream cheese, maple syrup to taste","Swirl: 20 g almond butter, 15 ml maple syrup, cinnamon, a tiny splash of milk","Maple syrup counted as 30 ml in total (15 ml swirl + about 15 ml to taste)","Servings not given in the original; counted as 1"],
  steps:["Mix all the pudding ingredients with the chia seeds (add a little milk if you want it thinner) and refrigerate 1–2 hours to thicken.","Mix the frosting and spread it over the chia pudding.","Mix the swirl and pipe it over the top.","Refrigerate overnight, then dust with cinnamon in the morning."]},
 {id:"romesco",name:"Romesco protein pasta",serves:5,time:"30 min",tags:["High protein","High fibre"],stated:"30 g protein · 30 g fibre per serving (with lentil pasta)",
  ing:[["roastpep",300],["sundried",20],["oil",54],["tofu",250],["cashew",100],["nutyeast",20],["tompaste",165],["soymilk",120],["pesto",15],["wwpasta",500]],
  extra:["1 tbsp smoked paprika, 1 tbsp sherry vinegar or a squeeze of lemon, ¼ tsp asafoetida","A handful of parsley, 1.5 tsp dried oregano, salt and black pepper","1–2 cups pasta water","Pasta counted as Napolina wholewheat; red lentil pasta raises the protein and fibre","Contains tofu and soya milk"],
  steps:["Blend all the sauce ingredients in a high-speed blender until completely smooth. Add up to 2 cups of pasta water to thin it out.","Cook the pasta as per the packet.","Warm the sauce on the hob if you like, then toss the pasta through it.","Top with roasted veg if you like."]},
 {id:"jalapenotoast",name:"Jalapeño popper toast",serves:1,time:"12 min",tags:["High protein"],stated:"375 kcal · 25 g protein · 38 g carbs · 12 g fat",
  ing:[["sourdough",60],["arla_lf",113],["cheddar",38],["jalapeno",20],["onion",20]],
  extra:["Bread: 1 thick slice of sourdough (counted as 60 g)","Cheese: ¼ cup grated cheddar in the mix plus a little extra on top (counted as 38 g)","Red onion: 2 tbsp, finely sliced"],
  steps:["Mix the cottage cheese with the chopped jalapeño, grated cheddar and red onion.","Spread onto the sourdough.","Top with more cheddar and extra jalapeño slices.","Air fry at 180°C for 8 minutes until golden, bubbly and crisp."]},
 {id:"gochutoast",name:"Gochujang onion cheese toasts",serves:2,time:"15 min",tags:["High protein"],stated:"400 kcal · 40 g protein · 30 g carbs · 16 g fat per 2 toasts",
  ing:[["tesco_paneer",100],["greek",30],["cheddar",45],["gochujang",25],["onion",80],["spinach",10],["sesame",10],["oil",3],["honey",4],["bread",160]],
  extra:["Makes 4 toasts; 1 serving = 2 toasts","½ tsp garlic powder, salt and black pepper","Spring onion or coriander to finish","Contains gochujang (soya)"],
  steps:["Mash the paneer until mostly smooth. Add the curd, cheese, gochujang, onion, spinach, garlic powder, salt and pepper and mix until creamy.","Toss the sliced onions with gochujang, oil, salt and honey. Sauté 2–3 minutes until soft and slightly caramelised.","Spread the paneer mix over the bread. Top with the gochujang onions and extra cheese.","Air fry at 185°C for 6–8 minutes until golden and crispy.","Finish with spring onion or coriander and sesame seeds."]},
 {id:"rajmabhurji",name:"Rajma paneer bhurji",serves:1,time:"15 min",tags:["High protein","High fibre"],stated:"368 kcal · 23.5 g protein",
  ing:[["ktc_rajma",100],["tesco_paneer",70],["onion",100],["tomato",120],["groundnutoil",2.5],["greenchilli",5],["yeo",245]],
  extra:["Cumin seeds, salt, red chilli powder, garam masala and turmeric to taste","Fresh coriander to garnish","Dahi counted as 1 cup of Yeo Valley natural yogurt"],
  steps:["Heat the oil and add cumin seeds, green chilli, onion and tomato. Sauté with the masalas until cooked.","Add the grated paneer and mashed rajma and mix well.","Stir in the whisked dahi, cook for a minute and finish with chopped coriander."]},
 {id:"palak2",name:"Palak paneer 2.0",serves:3,time:"30 min",tags:["High protein"],stated:"268 kcal · 20 g protein · 14 g carbs · 17 g fat",
  ing:[["mustardoil",20],["onion",120],["tomato",120],["spinach",235],["tesco_paneer",200]],
  extra:["1 tsp ginger-garlic paste, ½ tsp chilli powder, 1 tsp coriander powder, ¼ tsp turmeric, ½ tsp garam masala, salt","⅓ cup hot water for blending, fresh coriander","Tadka: ¾ tsp cumin seeds, 1 tsp Kashmiri chilli powder, 4–5 garlic cloves","Mustard oil is 1 tsp for the base + 1 tbsp for the tadka. About 300 g per serving."],
  steps:["Heat 1 tsp mustard oil and cook the sliced onions until properly golden.","Add the ginger-garlic paste and sauté until aromatic.","Add the chilli powder, coriander powder, turmeric and garam masala and cook briefly.","Add the tomato purée and salt and cook until thick and glossy.","Add the chopped palak and cook 2–3 minutes until wilted. Lower the flame.","Blend the paneer with the hot water until completely smooth.","Add the paneer sauce to the spinach and simmer gently for 1–2 minutes only.","For the tadka, heat 1 tbsp mustard oil, add cumin then garlic until lightly golden. Switch off the flame, add the Kashmiri chilli powder and pour straight over the curry.","Finish with coriander and serve with rice or roti."]},
 {id:"tikkasalad",name:"High-protein paneer tikka salad",serves:1,time:"25 min",tags:["High protein"],stated:"460 kcal · 47 g protein",
  ing:[["tesco_paneer",150],["yeo",30],["ghee",5],["greek",100],["oil",5],["cucumber",100],["carrot",60],["onion",40]],
  extra:["Marinade: haldi, mirch, dhaniya powder, garam masala","Sauce: garlic, mirch, dhaniya, salt, pepper","Salad veg amounts aren't given; counted as 100 g cucumber, 60 g carrot, 40 g onion","The original uses high-protein paneer; with that, protein is higher and fat lower than shown"],
  steps:["Mix the paneer with the curd, haldi, mirch, dhaniya powder and garam masala. Rest for 10 minutes.","Roast in 1 tsp ghee until crispy.","Blend the Greek yogurt with garlic, mirch, dhaniya, salt, pepper and a little olive oil until smooth.","Toss the cucumber, carrot, onion and paneer tikka with the sauce and enjoy."]},
 {id:"besansandwich",name:"Besan cheese sandwich",serves:1,time:"15 min",tags:["High protein"],stated:"460 kcal · 37 g protein",
  ing:[["bread",80],["besan",30],["tesco_paneer",50],["skyr",50],["mozz",50],["oil",5],["onion",50]],
  extra:["¼ tsp turmeric, ½ tsp Kashmiri red chilli powder, ½ tsp mustard seeds, curry leaves","½ tsp garlic powder, ½ tsp black pepper, ½ tsp chilli flakes, ½ tsp kasuri methi","Coriander leaves, salt, water"],
  steps:["On a plate, mix the besan, skyr, turmeric, red chilli powder, onion, coriander, salt and water to a pouring batter.","Heat the oil on a tawa and add the mustard seeds and curry leaves.","Dip each slice of bread in the batter and place on the tawa over a low flame.","Meanwhile, grate the paneer into a bowl with the mozzarella, garlic powder, kasuri methi, black pepper, chilli flakes and salt. Mix well.","Flip the bread. Spread the paneer mix on one slice and cover with the other.","Press down and cook on low for about 4 minutes, 2 minutes each side.","Cut and enjoy."]},
 {id:"poriyal",name:"Spinach chana poriyal",serves:1,time:"20 min",tags:["High fibre"],stated:"500 kcal · 20 g protein",
  ing:[["ktc_chick",150],["spinach",150],["peanuts",20],["coconut",30],["oil",10],["chanadal",15],["onion",200],["greenchilli",10]],
  extra:["1 tsp Kashmiri red chilli powder, 1 tsp mustard seeds, 1 tsp jeera, curry leaves, 2 dry red chillies, salt","A squeeze of lemon (helps iron absorption)","Coconut counted as fresh grated"],
  steps:["Heat the oil in a kadai.","Add the mustard seeds, jeera, chana dal, curry leaves, green chilli and dry red chilli.","Sauté on a low flame until the chana dal turns brown.","Add the onion and salt and sauté on a high flame for 4 minutes.","Add the chopped spinach and sauté on high for 4–5 minutes.","Add the boiled chana and mix on a high flame for 3 minutes.","Lower the flame. Coarsely blend the peanuts, coconut and red chilli powder and add to the kadai.","Mix for a minute, switch off the flame and squeeze over the lemon."]},
 {id:"besanomelette",name:"Vegetarian high-protein omelette",serves:1,time:"20 min",tags:["High protein","High fibre"],stated:"490 kcal · 42 g protein",
  ing:[["besan",40],["tesco_paneer",100],["mozz",30],["oil",5],["mushroom",100],["spinach",50],["tomato",240]],
  extra:["1 tsp black pepper, ½ tsp chilli flakes, salt, water, coriander leaves","Spinach amount isn't given; counted as 50 g","Uses low-fat paneer in the original; counted here as Tesco medium-fat"],
  steps:["Mix the besan with ½ tsp black pepper, the chilli flakes, salt and water to a thin dosa-style batter. Set aside.","Dry-heat a kadai, add the mushrooms and sauté on a high flame for 4–5 minutes.","Add the spinach, tomatoes, the rest of the pepper and salt. Sauté on high for 4 minutes and set aside.","Spray a pan with oil and keep it on a low flame.","Pour in the besan batter and spread it out slowly.","Top with the grated paneer, the mushroom-spinach mix, the cheese and coriander.","Cook on low for 3–4 minutes, fold carefully and cook on medium for 2–3 minutes more."]},
 {id:"chanapalak",name:"Chana palak masala",serves:2,time:"Soak overnight + 35 min",tags:["High protein","High fibre"],stated:"700 kcal · 49 g protein · 58 g carbs · 34 g fat · 16 g fibre for the whole dish",
  ing:[["kala_dry",75],["spinach",80],["tesco_paneer",150],["oil",20],["onion",60],["greenchilli",5]],
  extra:["1 tsp salt + ½ tsp salt, 1 cup water for cooking the chana, 150 ml water for blending","1 tsp cumin seeds, 1 tsp ginger-garlic paste","½ tsp turmeric, 1 tsp Kashmiri red chilli powder, 1 tsp coriander powder, 1 tsp kasuri methi","Fresh coriander to garnish","150 g soaked black chana counted as about 75 g dry. Regular chickpeas work too.","The original gives figures for the whole dish; split here into 2 servings"],
  steps:["Pressure cook the soaked black chana with 1 tsp salt and enough water to cover for 20 minutes, until soft. Set aside and keep the cooking water.","Blend the spinach, paneer and 150 ml water until smooth. Set aside.","Heat the oil in a pan on medium heat. Add the cumin seeds, onion, green chilli and ginger-garlic paste and sauté for 2 minutes.","Add the turmeric, Kashmiri chilli powder, coriander powder and kasuri methi. Mix well, then pour in 200 ml of the reserved chickpea water.","Add the spinach-paneer purée and cook for about 5 minutes, until the gravy starts to thicken.","Add ½ tsp salt and the cooked chickpeas. Mix and cook for another 2 minutes.","Garnish with fresh coriander and serve."]},
 {id:"paneersandwich",name:"Creamy paneer sandwich",serves:2,time:"15 min",tags:["High protein"],stated:"260 kcal · 16 g protein · 34 g carbs · 8 g fat per sandwich",
  ing:[["tesco_paneer",100],["greek",45],["onion",10],["carrot",10],["cucumber",10],["hovis_seed",176],["butter",10]],
  extra:["Paneer sauce: 2 garlic cloves, 1 tsp chilli flakes, 2 dried red chillies, 10 ml lemon or lime juice, 1 tsp salt","1 tbsp chopped coriander","Makes 2 sandwiches; 1 serving = 1 sandwich (2 slices of multigrain bread, counted as Hovis Seed Sensations)","Butter counted as 1 tsp per sandwich"],
  steps:["Blend the paneer, garlic, Greek yogurt, chilli flakes, dried red chillies, lemon juice and salt until smooth and creamy. Set aside.","In a bowl, mix the onion, carrot, cucumber and coriander.","Pour in the paneer sauce and mix everything together.","Spread half the filling on a slice of multigrain bread and close the sandwich.","Toast with 1 tsp butter until golden and crispy on both sides. Repeat for the second sandwich."]},
 {id:"malaipyaaz",name:"Rajasthani malai pyaaz",serves:2,time:"15 min",tags:["High protein"],stated:"600 kcal · 40 g protein · 23 g carbs · 40 g fat for the whole dish",
  ing:[["mustardoil",27],["onion",150],["greenchilli",10],["tesco_paneer",180]],
  extra:["1 tsp cumin seeds, 1 tbsp ginger-garlic paste","1 tsp salt, ½ tsp turmeric, 1 tbsp Kashmiri red chilli powder, 1 tsp coriander powder","150 ml water to blend the paneer","1 tsp amchur powder, 1 tsp kasuri methi, a handful of fresh coriander","The original gives figures for the whole dish; split here into 2 servings"],
  steps:["Heat 2 tbsp mustard oil in a pan on medium heat. Add the cumin seeds, onion, slit green chillies and ginger-garlic paste.","Cook for about 3 minutes, until the onions start to brown.","Add the salt, turmeric, Kashmiri chilli powder and coriander powder. Mix well.","Add the paneer blended with 150 ml water.","Add the amchur, kasuri methi and fresh coriander.","Mix and cook for another 2 minutes, then serve."]},
 {id:"curry",name:"Chickpea & spinach curry",serves:2,time:"25 min",tags:["High fibre","Vegan"],
  ing:[["ktc_chick",240],["spinach",160],["ktc_tom",400],["onion",100],["oil",10],["brownrice",360]],
  extra:["2 garlic cloves, 1 thumb ginger","1 tsp each cumin, garam masala, turmeric"],
  steps:["Soften the onion in the oil for 6 minutes, then add garlic, ginger and spices for 1 minute.","Tip in the tomatoes and drained chick peas and simmer for 12 minutes until thick.","Stir through the spinach until wilted, season, and serve over the rice."]},
 {id:"bhurji",name:"Paneer bhurji on toast",serves:1,time:"15 min",tags:["High protein"],
  ing:[["tesco_paneer",100],["ktc_tom",80],["onion",50],["spinach",40],["oil",5],["bread",80]],
  extra:["1 green chilli, ½ tsp turmeric, ½ tsp garam masala, coriander"],
  steps:["Fry the onion and chilli in the oil until soft, then add turmeric and the tomatoes for 3 minutes.","Crumble in the paneer with garam masala and cook 3 minutes.","Fold in the spinach and pile onto toasted bread."]},
 {id:"oats",name:"Protein overnight oats",serves:1,time:"5 min + overnight",tags:["High protein","High fibre"],
  ing:[["oats",50],["milb_straw",200],["milk",80],["chia",15],["strawberry",80]],
  extra:["½ tsp vanilla, pinch of cinnamon"],
  steps:["Stir the oats, yogurt, milk, chia and vanilla together in a jar.","Chill overnight.","Top with sliced strawberries in the morning."]},
 {id:"dal",name:"Red lentil dal",serves:3,time:"30 min",tags:["High fibre","Vegan"],
  ing:[["redlentil",200],["ktc_tom",400],["onion",150],["spinach",100],["oil",10]],
  extra:["3 garlic cloves, 1 tsp cumin seeds, 1 tsp turmeric, 750 ml water, lemon"],
  steps:["Fry onion and cumin seeds in the oil until soft.","Add garlic, turmeric, rinsed lentils, tomatoes and water; simmer 20 minutes, stirring.","Stir in spinach and a squeeze of lemon."]},
 {id:"kala",name:"Kala chana masala",serves:2,time:"25 min",tags:["High fibre","Vegan"],
  ing:[["ktc_kala",240],["ktc_tom",200],["onion",100],["oil",10],["brownrice",300]],
  extra:["2 garlic cloves, ginger, 1 tsp each cumin, coriander, garam masala, ½ tsp chilli, lemon"],
  steps:["Cook the onion in the oil until golden, add garlic, ginger and spices for 1 minute.","Add tomatoes and drained kala chana with a splash of water; simmer 12 minutes, mashing a few to thicken.","Finish with lemon and serve with rice."]},
 {id:"bowl",name:"Black bean & sweet potato bowl",serves:2,time:"35 min",tags:["High fibre","Vegan"],
  ing:[["blackbeans",240],["sweetpot",300],["quinoa",125],["avocado",100],["oil",10]],
  extra:["1 tsp smoked paprika, 1 lime, coriander"],
  steps:["Roast cubed sweet potato with the oil and paprika at 200°C for 25 minutes.","Warm the beans; cook the quinoa.","Build bowls and top with sliced avocado, lime and coriander."]},
 {id:"matar",name:"Matar paneer",serves:2,time:"25 min",tags:["High protein"],
  ing:[["tesco_paneer",160],["peas",200],["ktc_tom",200],["onion",100],["oil",10]],
  extra:["2 garlic cloves, ginger, 1 tsp garam masala, ½ tsp chilli powder"],
  steps:["Brown the paneer cubes in half the oil and set aside.","Cook onion, garlic and ginger in the rest of the oil, add spices and tomatoes, simmer 8 minutes.","Add peas and paneer and cook 5 minutes more."]},
 {id:"snack",name:"Cottage cheese crunch bowl",serves:1,time:"3 min",tags:["High protein"],
  ing:[["arla_lf",200],["apple",150],["pumpkin",20]],
  extra:["Cinnamon"],
  steps:["Spoon the cottage cheese into a bowl.","Top with chopped apple, pumpkin seeds and cinnamon."]},
 {id:"rajma",name:"Rajma chilli with cheese",serves:4,time:"35 min",tags:["High protein","High fibre"],
  ing:[["ktc_rajma",480],["ktc_blackeye",240],["ktc_tom",400],["onion",150],["oil",10],["brownrice",540],["eatlean",80]],
  extra:["2 tsp chilli powder, 1 tsp cumin, 1 pepper, 200 ml veg stock"],
  steps:["Soften onion and pepper in the oil, add spices for 1 minute.","Add drained beans, tomatoes and stock; simmer 20 minutes until thick.","Serve over rice with the grated cheese on top."]},
 {id:"toast",name:"Philly, strawberry & seed toast",serves:1,time:"5 min",tags:["High protein"],
  ing:[["bread",80],["phil_pro",60],["strawberry",80],["hemp",10]],
  extra:["Drizzle of honey (optional, not counted)"],
  steps:["Toast the bread.","Spread with the cream cheese.","Top with sliced strawberries and hemp seeds."]},
];

// Per-serving nutrition for each recipe, worked out from its ingredients.
RECIPES.forEach(r => {
  const t = { k: 0, p: 0, c: 0, f: 0, fi: 0 };
  r.ing.forEach(([id, g]) => {
    const fd = FOOD[id];
    if (!fd) return;
    for (const k in t) t[k] += (fd.n[k] || 0) * g / 100;
  });
  r.per = Object.fromEntries(Object.entries(t).map(([k, v]) => [k, v / r.serves]));
});
